### get hello
GET http://localhost:8888/hello


### get gw 1
GET http://localhost:8888/gw


### get ga 1
GET http://localhost:8888/ga/asda



### post userService1
POST http://localhost:8888/gw/lhtrpc/com.lht.lhtrpc.demo.api.UserService
Content-Type: application/json

{
  "service": "com.lht.lhtrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [200]
}

### post userService2
POST http://localhost:8888/gw/direct/com.lht.lhtrpc.demo.api.UserService
Content-Type: application/json

{
  "service": "com.lht.lhtrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [200]
}

### post userService backend
POST http://localhost:8888/gw/direct/com.lht.lhtrpc.demo.api.UserService?backend=http://localhost:8081/lhtrpc
Content-Type: application/json

{
  "service": "com.lht.lhtrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [200]
}

### post userService1
POST http://192.168.3.55:8081/lhtrpc
Content-Type: application/json

{
  "service": "com.lht.lhtrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [200]
}